### PR TITLE
Update quickcheck to 1.0

### LINKED ISSUE #148: Upgrade `quickcheck` to 1.0
The failure occurs with upgrading `quickcheck` to 1.0, like:

```
thread 'changes::tests::bchange_span_neq' panicked at '[quickcheck] TEST FAILED (runtime error). Arguments: ((DefId_(DefId { krate: crate3513719616, index: DefIndex(648839651) }), DefId_(DefId { krate: crate2679547491, index: DefIndex(1780828734) }), Span_(2279446622, 4173879214), Span_(1544354787, 2347583072), false, []), (DefId_(DefId { krate: crate2701441836, index: DefIndex(517410664) }), DefId_(DefId { krate: crate3641961060, index: DefIndex(3154559013) }), Span_(2629862979, 2776885218), Span_(3436779539, 3518299588), false, []))
Error: "cannot access a scoped thread local variable without calling `set` first"', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/quickcheck-1.0.1/src/tester.rs:165:28
```

Here's the full log: https://github.com/JohnTitor/rust-semverver/runs/1676268153
WIP commit: https://github.com/JohnTitor/rust-semverver/commit/b5d21b624de5639eb5c51355858321570cabc6d4

It'd be great if we could find the cause.

### PR DESCRIPTION
**Pull request by Xanewok**
Closes #148
Closes #157

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]
Thanks! Looks good to me, could you also add `closes #157` to the OP? I don't have permission for this repo and cannot close it by hand.

**Comment by Xanewok** [comment]
Done, although I think dependabot is smart enough to close pending PRs for deps that are not required anymore

**Comment by JohnTitor** [comment]
Ah, I forgot the bot can detect it. 
@bors r+

**Pull request merged**
