### PR TITLE
Upgrade rust toolchain

### PR DESCRIPTION
**Pull request by jdisanti**

### CODE REVIEW

**Comment by JohnTitor** [comment]
#91188 is a rustdoc PR, a wrong link?

**Comment by jdisanti** [comment]
I think I might be misunderstanding how to link these up correctly. My approach was to install a nightly with rustup, and then acquire its commit hash with `rustc +nightly-<version> --version`, and find the PR corresponding with that commit hash. How do you do it?

**Comment by JohnTitor** [comment]
That commit hash is just the latest commit of that nightly version. One nightly version usually contains some PRs merged in the master branch of rust-lang/rust, so we should bisect it to find a culprit PR. I use https://github.com/kennytm/rustup-toolchain-install-master to do bisection, and if it's a rollup PR, we should also look at it and find an exact culprit PR.

**Comment by jdisanti** [comment]
OK, that makes a lot more sense now! I will force push revised commits with the corrected PR references.

**Review by JohnTitor — APPROVED** [review]
LGTM, thanks for the links!

**Pull request merged**
