### PR TITLE
Housekeeping

### PR DESCRIPTION
**Pull request by Xanewok**
Fixing some artifacts of the past - this should not change any behaviour.

It's worth noting that there are some `allow` attributes for pedantic Clippy lints, which are not enforced anywhere anymore - probably because those lints have been moved around in categories. Should I remove the directives that do not warn anymore by default under `cargo clippy`?

r? @Manishearth

### CODE REVIEW

**Comment by Manishearth** [comment]
r=me

**Comment by Manishearth** [comment]
@Mark-Simulacrum  can you add @Xanewok and @ibabushkin as reviewers to this? It's fine to set this up as some sort of "semverver project group" under devtools too if necessary.

**Comment by Mark-Simulacrum** [comment]
I think someone else added those permissions? Uncertain.

**Comment by Xanewok** [comment]
I added permissions manually in https://github.com/rust-lang/team/pull/472 but maybe we should set up a separate project group as well.

It seems I need to add CI triggers for the `auto` branch as well

**Comment by Xanewok** [comment]
Let's try this again

@bors retry

**Pull request merged**
