### PR TITLE
Make it work again :)

### PR DESCRIPTION
**Pull request by orium**

### CODE REVIEW

**Comment by ibabushkin** [comment]
This looks pretty good, thank you! I'll have a more detailed look tomorrow and let you know whether any changes will be needed, or merge straightaway :)

**Comment by orium** [comment]
Travis is failing because when semver checks itself it will fail to compile the last published version of semver.

**Comment by orium** [comment]
:+1: Can you do a release soon?

**Comment by ibabushkin** [comment]
On 2018-09-16, Diogo Sousa wrote:
> :+1: Can you do a release soon?

Already done :)

**Pull request merged**
